title: Wilson Wei-Lun Chang # your name (or website title) here
logo: "/images/picture.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Engineer at <a href="https://www.qualcomm.com/">Qualcomm Technologies Inc.</a>
  <br>
  Email: luckchang6@gmail.com
  <br> 
  This is my <a href="cv.pdf">CV</a>
  <br>
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
